### ISSUE TITLE
Question regarding box label

### ISSUE THREAD

**Issue by YumTaha** [mgonzs13/yolo_ros#62]
I am working on understanding the `yolo_ros` Python file and its functions, going through each line to identify where things are defined and how to modify them. For instance, I want to edit the label text, colors, and other parameters, as well as understand the calculation process. However, there is limited documentation and comments explaining the functionality of each method or function. Is there a video or more detailed documentation available for these Python files?

![image](https://github.com/user-attachments/assets/b21d8a47-48de-42ab-b857-6b7ad95ad1ab)

**Comment by mgonzs13** [comment]
Labels are drawn here https://github.com/mgonzs13/yolo_ros/blob/d095b7a25562daee7cc568a3c9f9ed3f6fdad0b8/yolo_ros/yolo_ros/debug_node.py#L182

You can modify the label before this line.
