### ISSUE TITLE
Rviz2 not displaying the camera

### ISSUE THREAD

**Issue by prakash-aryan** [mgonzs13/yolo_ros#63]
I have a zed camera and I am running the yolo nodes through docker

![Screenshot 2024-12-09 171511](https://github.com/user-attachments/assets/84ad17f1-b41b-4fa9-b314-2d5009cff428)
![Screenshot 2024-12-09 171139](https://github.com/user-attachments/assets/d7e52d72-cb85-4f59-8d14-72ced069f88e)
![Screenshot 2024-12-09 171155](https://github.com/user-attachments/assets/8da3ef86-bde0-461f-9601-cea56ee809fa)
![Screenshot 2024-12-09 171312](https://github.com/user-attachments/assets/991c13db-ec09-4022-918a-e9803f8fe8c2)
![Screenshot 2024-12-09 171216](https://github.com/user-attachments/assets/83c900d8-61a7-459f-aaa9-99cea2292404)

**Comment by mgonzs13** [comment]
@prakash-aryan the `ros2 launch yolo_bringup yolo.launch.py` command is using default topics and params. You have to use your camera topics, for example, `ros2 launch yolo_bringup yolov5.launch.py input_image_topic:=<your topic>`. Take a look at the README to see the other [launch arguments](https://github.com/mgonzs13/yolo_ros?tab=readme-ov-file#parameters).

**Comment by prakash-aryan** [comment]
Yes it works now. 
Thanks a lot

I used - > 

` ros2 launch yolo_bringup yolo.launch.py input_image_topic:=/zed_camera/rgb/left_image use_debug:=True device:=cpu`

**Comment by Johnny-Hu-406** [comment]
When executing `ros2 topic echo /yolo/detections`, I can see the following output, and `ros2 topic echo /yolo/tracking` also has similar output.

![Image](https://github.com/user-attachments/assets/0fa8d458-2636-4dd3-90c9-9df0755dfc2a)
